app/workers/routes.py
"""Routes for workers section of main page"""

from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user

from app.models import Workplace, Function, Worker, StartDocType
from app.workers import bp
from app.workers.forms import NewWorkerForm, NewStartDocForm, FilterWorkersForm
from app.utils.utilities import required_role
from app.workers import workers_utils


@bp.route("/add-workers", methods=["GET", "POST"])
@login_required
def add_worker():
    """
    Adds new worker to db
    :return: redirects to created worker's start documents or, if worker already exists, gives user info about that
    """
    required_role(current_user, "user")

    title = "HR - nowy pracownik"

    form = NewWorkerForm()
    form.workplace.choices = [(str(worker), str(worker)) for worker in Workplace.query.all()]
    form.function.choices = [(str(function), str(function)) for function in Function.query.all()]
    if form.validate_on_submit():
        worker = workers_utils.add_worker_submit_form(form)
        if worker[0]:
            return redirect(url_for("workers.start_docs_required", worker_id=worker[1]))
        flash("Użytkownik {} już istnieje".format(form.name.data))

    return render_template("workers/add_worker.html", title=title, form=form)


@bp.route("/<worker_id>/start-docs-required", methods=["GET", "POST"])
@login_required
def start_docs_required(worker_id):
    """
    Allows to manage start documents of worker
    :param worker_id: worker's db id
    :return: renders template with list of all documents where user can choose which of them are needed to hire eworker
    """
    required_role(current_user, "user")

    worker = Worker.query.filter_by(id=worker_id).first()
    documents = StartDocType.query.order_by(StartDocType.id).all()

    title = "HR - wybór dokumentów do zatrudnienia"

    return render_template("workers/worker_select_start_docs.html", title=title, docs=documents, worker=worker)


@bp.route("/<worker_name>/create-start-docs", methods=["GET", "POST"])
@login_required
def create_start_docs(worker_name):
    """
    Creates records in db for each document user choose is required
    :param worker_name: worker's name
    :return: url for worker_start_docs
    """

    required_role(current_user, "user")

    data = request.json
    workers_utils.create_worker_start_docs(worker_name, data)

    return url_for("workers.worker_start_docs", worker_name=worker_name)


@bp.route("/worker_start-docs", methods=["GET", "POST"])
@login_required
def worker_start_docs():
    """
    Here user can check if worker delivered all documents needed for hire
    :return: index page if everything is OK
    """

    required_role(current_user, "user")

    worker_name = request.args.get("worker_name")
    worker = Worker.query.filter_by(name=worker_name).first()

    title = "HR dokumenty główne: {}".format(worker.name)

    form = NewStartDocForm()
    form.doc_type.choices = [(str(doc_type), str(doc_type)) for doc_type in StartDocType.query.all()]

    if form.validate_on_submit():
        doc = form.doc_type.data
        workers_utils.create_worker_start_docs(worker_name, [doc])
        return redirect(url_for("workers.worker_start_docs", worker_name=worker_name))

    return render_template("workers/worker_list_start_docs.html", title=title, docs=worker.start_docs, worker=worker,
                           form=form)


@bp.route("/start-docs-status-upgrade", methods=["GET", "POST"])
@login_required
def start_docs_status_upgrade():
    """
    Checks if data delivered by front is correct and upgrades start documents records
    :return: url to main page if data is correct. Else returns False
    """

    required_role(current_user, "user")

    data = request.json
    response = workers_utils.upgrade_start_docs_status(data)

    if response:
        return {"response": url_for("main.index")}

    return {"response": False}


@bp.route("/workers-query", methods=["GET", "POST"])
@login_required
def workers_query():
    """
    Allows to filter workers which user wants to find
    :return: list of workers meeting requirements
    """

    required_role(current_user, "user")

    title = "HR wyszukaj pracownika"

    form = FilterWorkersForm()
    form.workplace.choices = [(str(workplace), str(workplace)) for workplace in Workplace.query.all()]
    form.workplace.choices.insert(0, ("all", "wszystkie"))
    form.function.choices = [(str(function), str(function)) for function in Function.query.all()]
    form.function.choices.insert(0, ("all", "wszystkie"))
    if form.validate_on_submit():
        workers = workers_utils.query_workers(form)
        return render_template("workers/workers_list.html", workers=workers)

    return render_template("workers/workers_query.html", title=title, form=form)


@bp.route("/show-worker/<worker_id>", methods=["GET", "POST"])
@login_required
def show_worker(worker_id):
    """
    Shows important worker's info and allows to edit it
    :param worker_id: id of chosen worker
    :return: template with worker's info
    """

    required_role(current_user, "user")

    worker = Worker.query.filter_by(id=int(worker_id)).first()
    workplaces = Workplace.query.all()
    functions = Function.query.all()

    title = "HR dane pracownika {}".format(worker.name)

    return render_template("workers/show_worker.html", title=title, worker=worker, workplaces=workplaces,
                           functions=functions)


@bp.route("/edit-worker-basic", methods=["GET", "POST"])
@login_required
def edit_worker_basic():
    """
    Gets json with new workers data and updates records in database.
    Used by app/static/js/workers/edit_worker.js in app/templates/workers/show_worker.html
    :return: url for show_worker view
    """

    required_role(current_user, "user")

    data = request.json
    if not data["OK"]:
        return {"response": False}

    workers_utils.edit_worker_basic_info(data)

    return {"response": url_for("workers.show_worker", worker_id=data["worker_id"])}


@bp.route("/delete-worker/<worker_id>", methods=["GET", "POST"])
@login_required
def delete_worker(worker_id):
    """
    Deletes worker and all related documents and events
    :param worker_id: id of worker to be deleted
    :return: redirect back to main page
    """
    required_role(current_user, "user")

    if workers_utils.del_worker(worker_id) is True:
        flash("Pracownik usunięty")
    else:
        flash("Błąd. Upewnij się, że taki pracownik istnieje. Ktoś mógł go usunąć w międzyczasie.")

    return redirect(url_for("main.index"))

hr_helper/__init__.py
#-*- coding: utf-8 -*-
# pylint: disable=wrong-import-position, missing-docstring

from hr_helper.app import app, db
from hr_helper import models

from hr_helper.auth import bp as auth_bp
app.register_blueprint(auth_bp)

from hr_helper.main import bp as main_bp
app.register_blueprint(main_bp)

from hr_helper.workers import bp as workers_bp
app.register_blueprint(workers_bp)

from hr_helper.start_docs import bp as start_docs_bp
app.register_blueprint(start_docs_bp)

hr_helper/app.py
#-*- coding: utf-8 -*-
# pylint: disable=invalid-name, missing-docstring

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

from config import CONFIG_OBJECT


app = Flask(__name__)
app.config.from_object(CONFIG_OBJECT)

db = SQLAlchemy(app)
migrate = Migrate(app, db)

login = LoginManager(app)
login.login_view = 'auth.login'

hr_helper/main/__init__.py
# pylint: disable=missing-docstring

from hr_helper.main.routes import bp

hr_helper/main/routes.py
"""Routes for workers main page"""

from flask import Blueprint, render_template
from flask_login import login_required, current_user

from hr_helper.utils.utilities import required_role


bp = Blueprint("main", __name__)


@bp.route("/")
@bp.route("/index", methods=["GET", "POST"])
@login_required
def index():
    """
    Renders main page
    :return: main page if workers is logged
    """
    required_role(current_user, "user")

    title = "HR - strona główna"
    return render_template("main/main_page.html", title=title)

hr_helper/start_docs/__init__.py
# pylint: disable=missing-docstring

from hr_helper.start_docs.routes import bp

hr_helper/start_docs/routes.py
"""Routes for start documents (main documents) section of main page"""

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, current_user

from hr_helper.models import StartDocType
from hr_helper.utils.utilities import required_role
from hr_helper.start_docs.forms import NewStartDocTypeForm
from hr_helper.start_docs import start_docs_utils


bp = Blueprint("start_docs", __name__)


@bp.route("/new-start-doc-type", methods=["GET", "POST"])
@login_required
def new_start_doc_type():
    """
    Allows to create new type of main document (eg. job contract)
    :return: renders template with form for new start doc type
    """
    required_role(current_user, "user")

    title = "HR - nowy rodzaj dokumentu głównego"

    form = NewStartDocTypeForm()
    if form.validate_on_submit():
        if start_docs_utils.add_start_doc_type(form) is False:
            flash("Taki dokument już istnieje")
        else:
            flash("{} - nowy rodzaj dokumentu utworzony pomyślnie".format(form.name.data))

    return render_template("start_docs/new_start_doc_type.html", title=title, form=form)


@bp.route("/list-start-doc-type", methods=["GET", "POST"])
@login_required
def list_start_doc_type():
    """
    Allows to change name of start document type
    :return: renders template with list of all start document types
    """
    required_role(current_user, "user")

    types = StartDocType.query.all()

    title = "HR - lista rodzajów dokumentóœ głównych"

    return render_template("start_docs/start_doc_types_list.html", title=title, types=types)


@bp.route("/edit-start-doc-type", methods=["GET", "POST"])
@login_required
def edit_start_doc_type():
    """
    Changes name of start document type
    :return: "OK" if successful and "ERROR" if not
    """
    required_role(current_user, "user")

    data = request.json

    if start_docs_utils.change_start_doc_type_name(data) is False:
        return "ERROR"
    return "OK"


@bp.route("/delete-start-doc-type/<doctype_id>", methods=["GET", "POST"])
@login_required
def delete_start_doc_type(doctype_id):
    """
    Deletes given type of start document
    :param doctype_id: id of doctype to be deleted
    :return: redirect back to list of start doc types (list_start_doc_type() function)
    """
    required_role(current_user, "user")

    if start_docs_utils.remove_start_doctype(doctype_id) is True:
        flash("Typ dokumentu usunięty")
    else:
        flash("Błąd. Upewnij się, że taki typ dokumentu istnieje. Ktoś mógł go usunąć w międzyczasie.")
    return redirect(url_for("start_docs.list_start_doc_type"))

hr_helper/workers/__init__.py
# pylint: disable=missing-docstring

from hr_helper.workers.routes import bp

hr_helper/workers/routes.py
"""Routes for workers section of main page"""

from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user

from hr_helper.models import Workplace, Function, Worker, StartDocType
from hr_helper.workers.forms import NewWorkerForm, NewStartDocForm, FilterWorkersForm
from hr_helper.utils.utilities import required_role
from hr_helper.workers import workers_utils


bp = Blueprint("workers", __name__)


@bp.route("/add-worker", methods=["GET", "POST"])
@login_required
def add_worker():
    """
    Adds new worker to db
    :return: redirects to created worker's start documents or, if worker already exists, gives user info about that
    """
    required_role(current_user, "user")

    title = "HR - nowy pracownik"

    form = NewWorkerForm()
    form.workplace.choices = [(str(worker), str(worker)) for worker in Workplace.query.all()]
    form.function.choices = [(str(function), str(function)) for function in Function.query.all()]
    if form.validate_on_submit():
        worker = workers_utils.add_worker_submit_form(form)
        if worker[0]:
            return redirect(url_for("workers.start_docs_required", worker_id=worker[1]))
        flash("Użytkownik {} już istnieje".format(form.name.data))

    return render_template("workers/add_worker.html", title=title, form=form)


@bp.route("/<worker_id>/start-docs-required", methods=["GET", "POST"])
@login_required
def start_docs_required(worker_id):
    """
    Allows to manage start documents of worker
    :param worker_id: worker's db id
    :return: renders template with list of all documents where user can choose which of them are needed to hire eworker
    """
    required_role(current_user, "user")

    worker = Worker.query.filter_by(id=worker_id).first()
    documents = StartDocType.query.order_by(StartDocType.id).all()

    title = "HR - wybór dokumentów do zatrudnienia"

    return render_template("workers/worker_select_start_docs.html", title=title, docs=documents, worker=worker)


@bp.route("/<worker_name>/create-start-docs", methods=["GET", "POST"])
@login_required
def create_start_docs(worker_name):
    """
    Creates records in db for each document user choose is required
    :param worker_name: worker's name
    :return: url for worker_start_docs
    """

    required_role(current_user, "user")

    data = request.json
    workers_utils.create_worker_start_docs(worker_name, data)

    return url_for("workers.worker_start_docs", worker_name=worker_name)


@bp.route("/worker-start-docs", methods=["GET", "POST"])
@login_required
def worker_start_docs():
    """
    Here user can check if worker delivered all documents needed for hire
    :return: index page if everything is OK
    """

    required_role(current_user, "user")

    worker_name = request.args.get("worker_name")
    worker = Worker.query.filter_by(name=worker_name).first()

    title = "HR - dokumenty główne: {}".format(worker.name)

    form = NewStartDocForm()
    form.doc_type.choices = [(str(doc_type), str(doc_type)) for doc_type in StartDocType.query.all()]

    if form.validate_on_submit():
        doc = form.doc_type.data
        workers_utils.create_worker_start_docs(worker_name, [doc])
        return redirect(url_for("workers.worker_start_docs", worker_name=worker_name))

    return render_template("workers/worker_list_start_docs.html", title=title, docs=worker.start_docs, worker=worker,
                           form=form)


@bp.route("/start-docs-status-upgrade", methods=["GET", "POST"])
@login_required
def start_docs_status_upgrade():
    """
    Checks if data delivered by front is correct and updates start documents records
    :return: url to main page if data is correct. Else returns False
    """

    required_role(current_user, "user")

    data = request.json
    response = workers_utils.upgrade_start_docs_status(data)

    if response:
        return {"response": url_for("main.index")}

    return {"response": False}


@bp.route("/workers-query", methods=["GET", "POST"])
@login_required
def workers_query():
    """
    Allows to filter workers which user wants to find
    :return: list of workers meeting requirements
    """

    required_role(current_user, "user")

    title = "HR wyszukaj pracownika"

    form = FilterWorkersForm()
    form.workplace.choices = [(str(workplace), str(workplace)) for workplace in Workplace.query.all()]
    form.workplace.choices.insert(0, ("all", "wszystkie"))
    form.function.choices = [(str(function), str(function)) for function in Function.query.all()]
    form.function.choices.insert(0, ("all", "wszystkie"))
    if form.validate_on_submit():
        workers = workers_utils.query_workers(form)
        return render_template("workers/workers_list.html", workers=workers)

    return render_template("workers/workers_query.html", title=title, form=form)


@bp.route("/show-worker/<worker_id>", methods=["GET", "POST"])
@login_required
def show_worker(worker_id):
    """
    Shows important worker's info and allows to edit it
    :param worker_id: id of chosen worker
    :return: template with worker's info
    """

    required_role(current_user, "user")

    worker = Worker.query.filter_by(id=int(worker_id)).first()
    workplaces = Workplace.query.all()
    functions = Function.query.all()

    title = "HR dane pracownika {}".format(worker.name)

    return render_template("workers/show_worker.html", title=title, worker=worker, workplaces=workplaces,
                           functions=functions)


@bp.route("/edit-worker-basic", methods=["GET", "POST"])
@login_required
def edit_worker_basic():
    """
    Gets json with new workers data and updates records in database.
    Used by app/static/js/workers/edit_worker.js in app/templates/workers/show_worker.html
    :return: url for show_worker view
    """

    required_role(current_user, "user")

    data = request.json
    if not data["OK"]:
        return {"response": False}

    workers_utils.edit_worker_basic_info(data)

    return {"response": url_for("workers.show_worker", worker_id=data["worker_id"])}


@bp.route("/delete-worker/<worker_id>", methods=["GET", "POST"])
@login_required
def delete_worker(worker_id):
    """
    Deletes worker and all related documents and events
    :param worker_id: id of worker to be deleted
    :return: redirect back to main page
    """
    required_role(current_user, "user")

    if workers_utils.del_worker(worker_id) is True:
        flash("Pracownik usunięty")
    else:
        flash("Błąd. Upewnij się, że taki pracownik istnieje. Ktoś mógł go usunąć w międzyczasie.")

    return redirect(url_for("main.index"))

hr_helper/templates/workers/add_worker.html
{% extends "base.html" %}

{% block head %}
<link href="{{ url_for('static', filename='css/workers/new-worker.css') }}" rel="stylesheet">
{% endblock %}


{% block content %}

<div class="wrapper fadeInDown">
    <div id="formContent">
        <form action="" method="post" novalidate>
            {{ form.hidden_tag() }}
            <div id="new-worker-header">
                <h1>Nowy pracownik</h1>
            </div>
            <p>
                {{ form.name.label(class="fadeIn first input-label") }} {{ form.name(class="fadeIn first") }}<br>
                {% for error in form.name.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.contract_begin.label(class="fadeIn second input-label") }} {{ form.contract_begin(class="fadeIn second") }}<br>
                {% for error in form.contract_begin.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.contract_end.label(class="fadeIn third input-label") }} {{ form.contract_end(class="fadeIn third") }}<br>
                {% for error in form.contract_end.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.workplace.label(class="fadeIn fourth input-label") }} {{ form.workplace(class="fadeIn fourth") }}<br>
                {% for error in form.workplace.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.function.label(class="fadeIn fifth input-label") }} {{ form.function(class="fadeIn fifth") }}<br>
                {% for error in form.function.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>{{ form.submit(id="btn-submit", class="fadeIn sixth") }}</p>
            <br>
        </form>
    </div>
</div>

{% endblock %}

hr_helper/templates/workers/show_worker.html
{% extends "base.html" %}

{% block head %}
<link href="{{ url_for('static', filename='css/workers/show-worker.css') }}" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="{{ url_for('static', filename='js/workers/edit_worker.js') }}"></script>
{% endblock %}

{% block content %}
<input id="worker-id" type="hidden" value="{{ worker.id }}">
<div class="top-container">
    <div class="wrapper">
        <form id="change-basic" class="content" action="/edit-worker-basic" method="post" novalidate>
            <div class="header">
                Podstawowe informacje
            </div>
            <div class="row">
                <div class="col">
                    <div class="data">
                        Nazwisko i imię:
                    </div>
                </div>
                <div class="col">
                    <input id="name" class="data" value="{{ worker.name }}">
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="data">
                        Dział:
                    </div>
                </div>
                <div class="col">
                    <select id="workplace" class="data">
                        {% for workplace in workplaces %}
                            <option value="{{ workplace.id }}" {% if worker.workplace_id==workplace.id %} selected="checked" {% endif %}>{{ workplace.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="data">
                        Funkcja:
                    </div>
                </div>
                <div class="col">
                    <select id="function" class="data">
                        {% for function in functions %}
                            <option value="{{ function.id }}" {% if worker.function_id==function.id %} selected="checked" {% endif %}>{{ function.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="data">
                        Zatrudniony:
                    </div>
                </div>
                <div class="col">
                    <input id="contract-begin" type="date" class="data" value="{{ worker.contract_begin }}">
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="data">
                        Koniec obecnej umowy:
                    </div>
                </div>
                <div class="col">
                    <input id="contract-end" type="date" class="data" value="{{ worker.contract_end }}">
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="data">
                        Nadal pracuje:
                    </div>
                </div>
                <div class="col">
                    <select id="still-works" class="data">
                        <option value="True" {% if worker.working==True %} selected="selected"{% endif %}>TAK</option>
                        <option value="False" {% if worker.working==False %} selected="selected"{% endif %}>NIE</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="data">
                        Zakończył pracę:
                    </div>
                </div>
                <div class="col">
                    <input id="work-end" type="date" class="data" {% if worker.work_end != None %} value="{{ worker.work_end }}" {% endif %}>
                </div>
            </div>
            <hr>
            <div class="data-footer">
                <input id="del-url" type="hidden" value="{{ url_for('workers.delete_worker', worker_id=worker.id) }}">
                <button type="button" id="del-worker" class="btn-submit">!!! Usuń pracownika i wszystkie powiązane dokumenty !!!</button>
            </div>
            <hr>
            <div class="data-footer">
                <button type="submit" id="basic-submit" class="btn-submit">Zapisz zmiany</button>
            </div>
        </form>
    </div>
    <div class="wrapper">
        <div class="content">
            <div class="header">
                Dokumenty pracownika
            </div>
            <div class="data-footer">
                <a href="{{ url_for('workers.worker_start_docs', worker_name=worker.name)}}">Dokumenty główne</a>
            </div>
            <div class="data-footer">
                Zdarzenia
            </div>
        </div>
    </div>
</div>

{% endblock %}

hr_helper/templates/workers/worker_list_start_docs.html
{% extends "base.html" %}

{% block head %}
<link href="{{ url_for('static', filename='css/workers/worker-list-start-docs.css') }}" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="{{ url_for('static', filename='js/workers/list_start_docs.js') }}"></script>
{% endblock %}

{% block content %}
<div class="wrapper">
    <div class="formContent">
        <form id="change-start-docs-status" action="/start-docs-status-upgrade" method="post" novalidate>
            <table id="docs-list-table">
                <thead>
                    <tr>
                        <th class="th-left">Dokument</th>
                        <th>Dostarczony</th>
                        <th>Przekazany do kadr</th>
                        <th>Data przekazania do kadr</th>
                        <th class="th-right">Uwagi</th>
                    </tr>
                </thead>
                <tbody>
                    {% for doc in docs %}
                    <tr id="{{ doc.id }}" class="docs-data">
                        <td class="td-left">
                            {{ doc }}
                        </td>
                        <td>
                            <div class="custom-control custom-switch">
                                <input type="checkbox" {% if doc.delivered %} checked {% endif %} class="custom-control-input delivered" id="{{ doc.id }}-delivered" value="{{ doc }}">
                                <label class="custom-control-label input-label" for="{{ doc.id }}-delivered"></label>
                            </div>
                        </td>
                        <td>
                            <div class="custom-control custom-switch">
                                <input type="checkbox" {% if doc.sent_to_hr %} checked {% endif %} class="custom-control-input sent" id="{{ doc.id }}-sent-to-hr" value="{{ doc }}">
                                <label class="custom-control-label input-label" for="{{ doc.id }}-sent-to-hr"></label>
                            </div>
                        </td>
                        <td>
                            <input type="date" id="{{ doc }}-sent-date" class="transp-input sent-date" {% if doc.sent_date != None %} value="{{ doc.sent_date }}" {% endif %}>
                        </td>
                        <td class="td-right">
                            <textarea rows="2" id="{{ doc }}-notes" class="transp-input notes">
                                {%- if doc.notes != "0" or doc.notes != "None" %}{{ doc.notes }}{% endif -%}
                            </textarea>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="5">
                            <button id="submit-doc-changes" class="btn-submit">Aktualizuj</button>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </form>
    </div>
</div>

<div class="wrapper">
    <div class="formContent">
        <form action="" method="post" novalidate>
            {{ form.hidden_tag() }}
            {{ form.doc_type(id="doc_type", class="transp-input") }}<br>
            {{ form.submit(id="submit-doc-changes", class="btn-submit") }}
        </form>
    </div>
</div>

{% endblock %}

hr_helper/templates/workers/worker_select_start_docs.html
{% extends "base.html" %}

{% block head %}
<link href="{{ url_for('static', filename='css/workers/select-start-docs.css') }}" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="{{ url_for('static', filename='js/workers/select_start_docs.js') }}"></script>
{% endblock %}

{% block content %}

<div class="wrapper fadeInDown">
    <div id="formContent">
        <form action="/{{ worker }}/create-start-docs" method="post" novalidate>
            <div id="header">
                <h2>Wybierz dokumenty, które musi dostarczyć <span id="worker">{{ worker }}</span></h2>
            </div>
            <ul class="list-group">
                {% for doc in docs %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div class="custom-control custom-switch doc">
                        <input type="checkbox" checked class="custom-control-input" id="{{ doc }}" value="{{ doc }}">
                        <label class="custom-control-label input-label" for="{{ doc }}">{{ doc }}</label>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <div id="list-footer">
                <br>
                <button id="btn-submit">Dalej</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

hr_helper/templates/workers/workers_list.html
{% extends "base.html" %}

{% block head %}
<link href="{{ url_for('static', filename='css/workers/workers-list.css') }}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="wrapper">
    <div class="formContent">
        <table id="docs-list-table">
            <thead>
                <tr>
                    <th class="th-left">Pracownik</th>
                    <th>Funkcja</th>
                    <th>Dział</th>
                    <th class="th-right">Pracuje</th>
                </tr>
            </thead>
            <tbody>
                {% for worker in workers %}
                <tr>
                    <td class="td-left">
                        <a href="{{ url_for('workers.show_worker', worker_id=worker.id) }}">{{ worker.name }}</a>
                    </td>
                    <td>
                        {{ worker.function }}
                    </td>
                    <td>
                        {{ worker.workplace }}
                    </td>
                    <td class="td-right">
                        {% if worker.working %} TAK
                        {% else %} NIE {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}