hr_helper/start_docs/forms.py
"""Forms for start documents section"""

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class NewStartDocTypeForm(FlaskForm):
    """Form for creating new type of starting document"""

    name = StringField("Nazwa dokumentu", validators=[DataRequired()])
    submit = SubmitField("Zatwierdź")

hr_helper/workers/forms.py
"""Forms for Worker section"""

from flask_wtf import FlaskForm
from wtforms import StringField, DateField, SelectField, SubmitField
from wtforms.validators import DataRequired, Optional


class NewWorkerForm(FlaskForm):
    """Form for new worker"""

    name = StringField("Imię i nazwisko", validators=[DataRequired()])
    contract_begin = DateField("Początek umowy", validators=[DataRequired()], format="%d.%m.%Y",
                               render_kw={"placeholder": "dd.mm.rrrr"})
    contract_end = DateField("Koniec umowy", validators=[DataRequired()], format="%d.%m.%Y",
                             render_kw={"placeholder": "dd.mm.rrrr"})
    function = SelectField("Stanowisko")
    workplace = SelectField("Dział")
    submit = SubmitField("Wprowadź")


class NewStartDocForm(FlaskForm):
    """Form for new start document for worker"""

    doc_type = SelectField("Typ dokumentu")
    submit = SubmitField("Dodaj")


class FilterWorkersForm(FlaskForm):
    """Fields to filter workers"""

    name = StringField("Imię i nazwisko", validators=[Optional()])
    works = SelectField("Pracuje", choices=[("all", "wszyscy"), ("True", "TAK"), ("False", "NIE")])
    workplace = SelectField("Dział")
    function = SelectField("Funkcja")
    submit = SubmitField("Szukaj")

app/main/routes.py
"""Routes for workers main page"""

from flask import render_template
from flask_login import login_required, current_user

from app.main import bp
from app.utils.utilities import required_role


@bp.route("/")
@bp.route("/index", methods=["GET", "POST"])
@login_required
def index():
    """
    Renders main page
    :return: main page if workers is logged
    """
    required_role(current_user, "user")

    title = "HR - strona główna"
    return render_template("main/main_page.html", title=title)

hr_helper/__init__.py
#-*- coding: utf-8 -*-
# pylint: disable=wrong-import-position, missing-docstring

from hr_helper.app import app, db
from hr_helper import models

from hr_helper.auth import bp as auth_bp
app.register_blueprint(auth_bp)

from hr_helper.main import bp as main_bp
app.register_blueprint(main_bp)

from hr_helper.workers import bp as workers_bp
app.register_blueprint(workers_bp)

from hr_helper.start_docs import bp as start_docs_bp
app.register_blueprint(start_docs_bp)

hr_helper/app.py
#-*- coding: utf-8 -*-
# pylint: disable=invalid-name, missing-docstring

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

from config import CONFIG_OBJECT


app = Flask(__name__)
app.config.from_object(CONFIG_OBJECT)

db = SQLAlchemy(app)
migrate = Migrate(app, db)

login = LoginManager(app)
login.login_view = 'auth.login'

hr_helper/main/__init__.py
# pylint: disable=missing-docstring

from hr_helper.main.routes import bp

hr_helper/main/routes.py
"""Routes for workers main page"""

from flask import Blueprint, render_template
from flask_login import login_required, current_user

from hr_helper.utils.utilities import required_role


bp = Blueprint("main", __name__)


@bp.route("/")
@bp.route("/index", methods=["GET", "POST"])
@login_required
def index():
    """
    Renders main page
    :return: main page if workers is logged
    """
    required_role(current_user, "user")

    title = "HR - strona główna"
    return render_template("main/main_page.html", title=title)

hr_helper/start_docs/__init__.py
# pylint: disable=missing-docstring

from hr_helper.start_docs.routes import bp

hr_helper/start_docs/routes.py
"""Routes for start documents (main documents) section of main page"""

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, current_user

from hr_helper.models import StartDocType
from hr_helper.utils.utilities import required_role
from hr_helper.start_docs.forms import NewStartDocTypeForm
from hr_helper.start_docs import start_docs_utils


bp = Blueprint("start_docs", __name__)


@bp.route("/new-start-doc-type", methods=["GET", "POST"])
@login_required
def new_start_doc_type():
    """
    Allows to create new type of main document (eg. job contract)
    :return: renders template with form for new start doc type
    """
    required_role(current_user, "user")

    title = "HR - nowy rodzaj dokumentu głównego"

    form = NewStartDocTypeForm()
    if form.validate_on_submit():
        if start_docs_utils.add_start_doc_type(form) is False:
            flash("Taki dokument już istnieje")
        else:
            flash("{} - nowy rodzaj dokumentu utworzony pomyślnie".format(form.name.data))

    return render_template("start_docs/new_start_doc_type.html", title=title, form=form)


@bp.route("/list-start-doc-type", methods=["GET", "POST"])
@login_required
def list_start_doc_type():
    """
    Allows to change name of start document type
    :return: renders template with list of all start document types
    """
    required_role(current_user, "user")

    types = StartDocType.query.all()

    title = "HR - lista rodzajów dokumentóœ głównych"

    return render_template("start_docs/start_doc_types_list.html", title=title, types=types)


@bp.route("/edit-start-doc-type", methods=["GET", "POST"])
@login_required
def edit_start_doc_type():
    """
    Changes name of start document type
    :return: "OK" if successful and "ERROR" if not
    """
    required_role(current_user, "user")

    data = request.json

    if start_docs_utils.change_start_doc_type_name(data) is False:
        return "ERROR"
    return "OK"


@bp.route("/delete-start-doc-type/<doctype_id>", methods=["GET", "POST"])
@login_required
def delete_start_doc_type(doctype_id):
    """
    Deletes given type of start document
    :param doctype_id: id of doctype to be deleted
    :return: redirect back to list of start doc types (list_start_doc_type() function)
    """
    required_role(current_user, "user")

    if start_docs_utils.remove_start_doctype(doctype_id) is True:
        flash("Typ dokumentu usunięty")
    else:
        flash("Błąd. Upewnij się, że taki typ dokumentu istnieje. Ktoś mógł go usunąć w międzyczasie.")
    return redirect(url_for("start_docs.list_start_doc_type"))

hr_helper/workers/__init__.py
# pylint: disable=missing-docstring

from hr_helper.workers.routes import bp

hr_helper/workers/routes.py
"""Routes for workers section of main page"""

from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user

from hr_helper.models import Workplace, Function, Worker, StartDocType
from hr_helper.workers.forms import NewWorkerForm, NewStartDocForm, FilterWorkersForm
from hr_helper.utils.utilities import required_role
from hr_helper.workers import workers_utils


bp = Blueprint("workers", __name__)


@bp.route("/add-worker", methods=["GET", "POST"])
@login_required
def add_worker():
    """
    Adds new worker to db
    :return: redirects to created worker's start documents or, if worker already exists, gives user info about that
    """
    required_role(current_user, "user")

    title = "HR - nowy pracownik"

    form = NewWorkerForm()
    form.workplace.choices = [(str(worker), str(worker)) for worker in Workplace.query.all()]
    form.function.choices = [(str(function), str(function)) for function in Function.query.all()]
    if form.validate_on_submit():
        worker = workers_utils.add_worker_submit_form(form)
        if worker[0]:
            return redirect(url_for("workers.start_docs_required", worker_id=worker[1]))
        flash("Użytkownik {} już istnieje".format(form.name.data))

    return render_template("workers/add_worker.html", title=title, form=form)


@bp.route("/<worker_id>/start-docs-required", methods=["GET", "POST"])
@login_required
def start_docs_required(worker_id):
    """
    Allows to manage start documents of worker
    :param worker_id: worker's db id
    :return: renders template with list of all documents where user can choose which of them are needed to hire eworker
    """
    required_role(current_user, "user")

    worker = Worker.query.filter_by(id=worker_id).first()
    documents = StartDocType.query.order_by(StartDocType.id).all()

    title = "HR - wybór dokumentów do zatrudnienia"

    return render_template("workers/worker_select_start_docs.html", title=title, docs=documents, worker=worker)


@bp.route("/<worker_name>/create-start-docs", methods=["GET", "POST"])
@login_required
def create_start_docs(worker_name):
    """
    Creates records in db for each document user choose is required
    :param worker_name: worker's name
    :return: url for worker_start_docs
    """

    required_role(current_user, "user")

    data = request.json
    workers_utils.create_worker_start_docs(worker_name, data)

    return url_for("workers.worker_start_docs", worker_name=worker_name)


@bp.route("/worker-start-docs", methods=["GET", "POST"])
@login_required
def worker_start_docs():
    """
    Here user can check if worker delivered all documents needed for hire
    :return: index page if everything is OK
    """

    required_role(current_user, "user")

    worker_name = request.args.get("worker_name")
    worker = Worker.query.filter_by(name=worker_name).first()

    title = "HR - dokumenty główne: {}".format(worker.name)

    form = NewStartDocForm()
    form.doc_type.choices = [(str(doc_type), str(doc_type)) for doc_type in StartDocType.query.all()]

    if form.validate_on_submit():
        doc = form.doc_type.data
        workers_utils.create_worker_start_docs(worker_name, [doc])
        return redirect(url_for("workers.worker_start_docs", worker_name=worker_name))

    return render_template("workers/worker_list_start_docs.html", title=title, docs=worker.start_docs, worker=worker,
                           form=form)


@bp.route("/start-docs-status-upgrade", methods=["GET", "POST"])
@login_required
def start_docs_status_upgrade():
    """
    Checks if data delivered by front is correct and updates start documents records
    :return: url to main page if data is correct. Else returns False
    """

    required_role(current_user, "user")

    data = request.json
    response = workers_utils.upgrade_start_docs_status(data)

    if response:
        return {"response": url_for("main.index")}

    return {"response": False}


@bp.route("/workers-query", methods=["GET", "POST"])
@login_required
def workers_query():
    """
    Allows to filter workers which user wants to find
    :return: list of workers meeting requirements
    """

    required_role(current_user, "user")

    title = "HR wyszukaj pracownika"

    form = FilterWorkersForm()
    form.workplace.choices = [(str(workplace), str(workplace)) for workplace in Workplace.query.all()]
    form.workplace.choices.insert(0, ("all", "wszystkie"))
    form.function.choices = [(str(function), str(function)) for function in Function.query.all()]
    form.function.choices.insert(0, ("all", "wszystkie"))
    if form.validate_on_submit():
        workers = workers_utils.query_workers(form)
        return render_template("workers/workers_list.html", workers=workers)

    return render_template("workers/workers_query.html", title=title, form=form)


@bp.route("/show-worker/<worker_id>", methods=["GET", "POST"])
@login_required
def show_worker(worker_id):
    """
    Shows important worker's info and allows to edit it
    :param worker_id: id of chosen worker
    :return: template with worker's info
    """

    required_role(current_user, "user")

    worker = Worker.query.filter_by(id=int(worker_id)).first()
    workplaces = Workplace.query.all()
    functions = Function.query.all()

    title = "HR dane pracownika {}".format(worker.name)

    return render_template("workers/show_worker.html", title=title, worker=worker, workplaces=workplaces,
                           functions=functions)


@bp.route("/edit-worker-basic", methods=["GET", "POST"])
@login_required
def edit_worker_basic():
    """
    Gets json with new workers data and updates records in database.
    Used by app/static/js/workers/edit_worker.js in app/templates/workers/show_worker.html
    :return: url for show_worker view
    """

    required_role(current_user, "user")

    data = request.json
    if not data["OK"]:
        return {"response": False}

    workers_utils.edit_worker_basic_info(data)

    return {"response": url_for("workers.show_worker", worker_id=data["worker_id"])}


@bp.route("/delete-worker/<worker_id>", methods=["GET", "POST"])
@login_required
def delete_worker(worker_id):
    """
    Deletes worker and all related documents and events
    :param worker_id: id of worker to be deleted
    :return: redirect back to main page
    """
    required_role(current_user, "user")

    if workers_utils.del_worker(worker_id) is True:
        flash("Pracownik usunięty")
    else:
        flash("Błąd. Upewnij się, że taki pracownik istnieje. Ktoś mógł go usunąć w międzyczasie.")

    return redirect(url_for("main.index"))

hr_helper/templates/main/main_page.html
{% extends "base.html" %}

{% block head %}
<link href="{{ url_for('static', filename='css/main/main.css') }}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="main-container">
    <div class="card func-group" style="width: 18rem;">
        <div class="card-header">
            <h2>Pracownicy</h2>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <button class="btn-main-link"><a href="{{ url_for('workers.add_worker') }}" class="a-btn-main">Nowy pracownik</a></button>
            </li>
            <li class="list-group-item">
                <button class="btn-main-link"><a href="{{ url_for('workers.workers_query') }}" class="a-btn-main">Wyszukaj pracownika</a></button>
            </li>
        </ul>
    </div>
    <div class="card func-group" style="width: 18rem;">
        <div class="card-header">
            <h2>Użytkownicy</h2>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <button class="btn-main-link"><a href="#" class="a-btn-main">Nowy użytkownik</a></button>
            </li>
            <li class="list-group-item">
                <button class="btn-main-link"><a href="#" class="a-btn-main">Edytuj użytkownika</a></button>
            </li>
        </ul>
    </div>
    <div class="card func-group" style="width: 18rem;">
        <div class="card-header">
            <h2>Dokumenty główne</h2>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <button class="btn-main-link"><a href="{{ url_for('start_docs.new_start_doc_type') }}" class="a-btn-main">Nowy dokument</a></button>
            </li>
            <li class="list-group-item">
                <button class="btn-main-link"><a href="{{ url_for('start_docs.list_start_doc_type') }}" class="a-btn-main">Edytuj/usuń dokument</a></button>
            </li>
        </ul>
    </div>
    <div class="card func-group" style="width: 18rem;">
        <div class="card-header">
            <h2>Działy</h2>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <button class="btn-main-link"><a href="#" class="a-btn-main">Nowy dział</a></button>
            </li>
            <li class="list-group-item">
                <button class="btn-main-link"><a href="#" class="a-btn-main">Edytuj dział</a></button>
            </li>
            <li class="list-group-item">
                <button class="btn-main-link"><a href="#" class="a-btn-main">Usuń dział</a></button>
            </li>
        </ul>
    </div>
    <div class="card func-group" style="width: 18rem;">
        <div class="card-header">
            <h2>Zdarzenia</h2>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <button class="btn-main-link"><a href="#" class="a-btn-main">Stwórz typ zdarzenia</a></button>
            </li>
            <li class="list-group-item">
                <button class="btn-main-link"><a href="#" class="a-btn-main">Nowe zdarzenie</a></button>
            </li>
            <li class="list-group-item">
                <button class="btn-main-link"><a href="#" class="a-btn-main">Lista zdarzeń</a></button>
            </li>
            <li class="list-group-item">
                <button class="btn-main-link"><a href="#" class="a-btn-main">Zestawienie zdarzeń</a></button>
            </li>
        </ul>
    </div>
</div>
{% endblock %}